### Import Pandas

In [1]:
import pandas as pd

### Cria um DF(Data Frame) manualmente

In [2]:
df = pd.DataFrame (
    {
        "Name": [
            "Pedro", 
            "Henrique",
            "Julia"
        ],
        "Age": [23, 24, 22],
        "Sex": ["male", "male", "female"]
    }
)

df

       Name  Age     Sex
0     Pedro   23    male
1  Henrique   24    male
2     Julia   22  female

### Cada coluna em um *DataFrame* é um número de séries

In [3]:
df["Age"]

0    23
1    24
2    22
Name: Age, dtype: int64

### OBS: Ao selecionar uma única coluna de um pandas DataFrame, o resultado é um pandas Series. Para selecionar a coluna, use o rótulo da coluna entre colchetes [].

### Series podem ser criados do zero também:

In [7]:
ages = pd.Series([20, 18, 32], name="Age")

ages

0    20
1    18
2    32
Name: Age, dtype: int64

In [9]:
df["Age"].max()

24

In [8]:
ages.max()

32

In [10]:
df.describe()

        Age
count   3.0
mean   23.0
std     1.0
min    22.0
25%    22.5
50%    23.0
75%    23.5
max    24.0

In [15]:
titanic = pd.read_csv('data/titanic.csv')

### O pandas fornece a read_csv()função para ler dados armazenados como um arquivo csv em um pandas DataFrame. O pandas suporta muitos formatos de arquivo ou fontes de dados diferentes prontos para uso (csv, excel, sql, json, parquet, …), cada um deles com o prefixo read_*.

In [16]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [19]:
titanic.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

### Verificar como o pandas interpretou cada um dos tipos de dados das colunas consultando o dtypesatributo do pandas:

In [20]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object