1.  Importe o arquivo alunos.csv e armazene seu conteúdo em um DataFrame Pandas.

In [3]:
import pandas as pd

In [1]:
url_alunos = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

In [7]:
df = pd.read_csv(url_alunos)
df

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

2) Visualize as primeiras 7 linhas do DataFrame e as 5 últimas.

In [8]:
df.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [9]:
df.tail()

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

3) Confira a quantidade de linhas e colunas desse DataFrame.

In [10]:
df.shape

(18, 4)

4) Explore as colunas do DataFrame e analise os tipos dos dados presentes em cada coluna.

In [13]:
df.columns

Index(['Nome', 'Idade', 'Notas', 'Aprovado'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      18 non-null     object
 1   Idade     18 non-null     int64
 2   Notas     12 non-null     float64
 3   Aprovado  18 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 582.0+ bytes

Extra: Calcule algumas estatísticas descritivas básicas dos dados do DataFrame (média, desvio padrão, etc).

Média:

In [33]:
media_geral_notas = df['Notas'].describe()['mean']
print(f"A média geral de notas é:{media_geral_notas}")

A média geral de notas é:6.8

Desvio:

In [41]:
desvio = df['Notas'].describe().std()
print(desvio)

3.3984177113071765

Menor nota:

In [46]:
menor_nota = df['Notas'].describe().min()
print(f"A menor nota é: {menor_nota:.1f}")

A menor nota é: 2.2

Maior nota:

In [47]:
maior_nota = df['Notas'].describe().max()
print(f"A maior nota é: {maior_nota:.1f}")

A maior nota é: 12.0

## Testes:

In [49]:
df_animais = pd.DataFrame({
   'Animal': ['Cachorro', 'Gato', 'Elefante', 'Cachorro', 'Gato', 'Elefante'],
   'Cor': ['Preto', 'Branco', 'Cinza', 'Marrom', 'Preto', 'Marrom'],
   'Quantidade': [2, 3, 1, 4, 2, 2]
})
df_animais

     Animal     Cor  Quantidade
0  Cachorro   Preto           2
1      Gato  Branco           3
2  Elefante   Cinza           1
3  Cachorro  Marrom           4
4      Gato   Preto           2
5  Elefante  Marrom           2

Utilizar o groupby para agrupar os dados pelo tipo de animal e realizarmos a soma da coluna "Quantidade" para conferirmos o total de cada tipo de animal:

In [51]:
df_animais.groupby('Animal').sum(numeric_only=True)

          Quantidade
Animal
Cachorro           6
Elefante           3
Gato               5

Usar o método groupby para agrupar os dados por múltiplas colunas. Por exemplo, vamos agrupar pelo tipo do animal e também pela cor e realizar a soma da coluna "Quantidade":

In [53]:
df_animais.groupby(['Animal', 'Cor'])[['Quantidade']].sum()

                 Quantidade
Animal   Cor
Cachorro Marrom           4
         Preto            2
Elefante Cinza            1
         Marrom           2
Gato     Branco           3
         Preto            2